### ISSUE TITLE
GH Actions publishes new versions whenever a branch is pushed

### ISSUE THREAD

**Issue by sam-qordoba** [Qordobacode/replaCy#54]
We need to pull apart that build release script, and only run the release part with the following condition

```
on:
  push:
    branches:
      - master
```

I will work on this right now, but FYI @lucfons
